/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package customer;

/**
 *
 * @author noure
 */
public class Customer extends javax.swing.JFrame {
    private String vehiclePlate;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Customer.class.getName());
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        new Customer().setVisible(true);
    });
}
    /**
     * Creates new form Customer
     */
   public Customer() {
    initComponents(); 

    models.User user = system.SessionManager.getCurrentUser();
    welcomeLabel.setText("Welcome, " + user.getUsername());
    vehiclePlate = ((models.Customer) user).getVehiclePlate();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        printTicketButton = new javax.swing.JButton();
        payTicketButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticketInfoArea = new javax.swing.JTextArea();
        welcomeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        printTicketButton.setText("Print Entry Ticket");
        printTicketButton.addActionListener(this::printTicketButtonActionPerformed);

        payTicketButton.setText("Pay for Parking");
        payTicketButton.addActionListener(this::payTicketButtonActionPerformed);

        ticketInfoArea.setColumns(20);
        ticketInfoArea.setRows(5);
        jScrollPane1.setViewportView(ticketInfoArea);

        welcomeLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(printTicketButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payTicketButton)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(welcomeLabel)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printTicketButton)
                    .addComponent(payTicketButton))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTicketButtonActionPerformed
        printTicket();
    }//GEN-LAST:event_printTicketButtonActionPerformed

    private void payTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payTicketButtonActionPerformed
        payForParking();
    }//GEN-LAST:event_payTicketButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Customer().setVisible(true));
    }

private void printTicket() {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Print Ticket logic هنا");
}

private void payForParking() {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Pay logic هنا");
}


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton payTicketButton;
    private javax.swing.JButton printTicketButton;
    private javax.swing.JTextArea ticketInfoArea;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
