/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package customer;
import models. Ticket;
import auth.LoginFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author noure
 */
public class Customer extends javax.swing.JFrame {
    private String vehiclePlate;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Customer.class.getName());

    /**
     * Creates new form Customer
     */
   public Customer() {
    initComponents(); 

    models.User user = system.SessionManager.getCurrentUser();
    welcomeLabel.setText("Welcome, " + user.getUsername());
    vehiclePlate = ((models.Customer) user).getVehiclePlate();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        printTicketButton = new javax.swing.JButton();
        payTicketButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticketInfoArea = new javax.swing.JTextArea();
        welcomeLabel = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parking System | Customer");

        printTicketButton.setText("Print Entry Ticket");
        printTicketButton.addActionListener(this::printTicketButtonActionPerformed);

        payTicketButton.setText("Pay for Parking");
        payTicketButton.addActionListener(this::payTicketButtonActionPerformed);

        ticketInfoArea.setEditable(false);
        ticketInfoArea.setColumns(20);
        ticketInfoArea.setRows(5);
        jScrollPane1.setViewportView(ticketInfoArea);

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLabel.setText("Welcome");

        btnback.setText("Back");
        btnback.addActionListener(this::btnbackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(printTicketButton)
                .addGap(18, 18, 18)
                .addComponent(payTicketButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnback)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(printTicketButton)
                            .addComponent(payTicketButton))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnback)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTicketButtonActionPerformed
        printTicket();
    }//GEN-LAST:event_printTicketButtonActionPerformed

    private void payTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payTicketButtonActionPerformed
        payForParking();
    }//GEN-LAST:event_payTicketButtonActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Customer().setVisible(true));
    }

private void printTicket() {

    currentTicket = new Ticket(
            "TKT" + (int)(Math.random() * 10000),
            "SPOT9",
            "ABC123"
    );

    String entryTime =
            currentTicket.getEntryTime()
                    .format(java.time.format.DateTimeFormatter
                            .ofPattern("yyyy-MM-dd HH:mm:ss"));

    ticketInfoArea.setText(
            "=== PARKING TICKET ===\n" +
            "Ticket ID: " + currentTicket.getTicketId() + "\n" +
            "Vehicle Plate: " + currentTicket.getVehiclePlate() + "\n" +
            "Spot ID: " + currentTicket.getSpotId() + "\n" +
            "Entry Time: " + entryTime + "\n\n" +
            "Please keep this ticket for exit!"
    );

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Ticket printed successfully!\nTicket ID: "
                    + currentTicket.getTicketId()
    );
}

private void payForParking() {

    if (currentTicket == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No ticket found!"
        );
        return;
    }

    String input = javax.swing.JOptionPane.showInputDialog(
            this,
            "Enter your Ticket ID:"
    );

    if (input == null || input.trim().isEmpty()) {
        return;
    }

    if (!input.equals(currentTicket.getTicketId())) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Invalid Ticket ID!"
        );
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Confirm payment?",
            "Payment Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirm != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    currentTicket.setExitTime(java.time.LocalDateTime.now());
    double amount = currentTicket.calculateAmountDue();
    currentTicket.setAmountPaid(amount);

    String entryTime =
            currentTicket.getEntryTime()
                    .format(java.time.format.DateTimeFormatter
                            .ofPattern("yyyy-MM-dd HH:mm:ss"));

    String exitTime =
            currentTicket.getExitTime()
                    .format(java.time.format.DateTimeFormatter
                            .ofPattern("yyyy-MM-dd HH:mm:ss"));

    ticketInfoArea.setText(
            "=== PAYMENT RECEIPT ===\n" +
            "Ticket ID: " + currentTicket.getTicketId() + "\n" +
            "Vehicle: " + currentTicket.getVehiclePlate() + "\n" +
            "Parking Spot: " + currentTicket.getSpotId() + "\n" +
            "Entry Time: " + entryTime + "\n" +
            "Exit Time: " + exitTime + "\n" +
            "Hours Parked: " + currentTicket.getParkedHours() + "\n" +
            "Amount Paid: $" + String.format("%.2f", amount) + "\n\n" +
            "Have a safe journey!"
    );
}
 
    private Ticket currentTicket;

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton payTicketButton;
    private javax.swing.JButton printTicketButton;
    private javax.swing.JTextArea ticketInfoArea;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables


}
