
package operator;

/**
 *
 * @author youse
 */
public class ExitOperator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExitOperator.class.getName());

    /**
     * Creates new form ExitOperator
     */
    public ExitOperator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ticketIdField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        calculationArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exit opertator");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Parking Exit Station");
        jLabel1.setName("titleLabel "); // NOI18N

        jLabel2.setText("Enter Ticket ID: ");

        ticketIdField.setName("ticketIdField "); // NOI18N
        ticketIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketIdFieldActionPerformed(evt);
            }
        });

        calculateButton.setText("Calculate Hours ");
        calculateButton.setName("calculateButton "); // NOI18N
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        clearButton.setText("clear");
        clearButton.setName("clearButton "); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        calculationArea.setEditable(false);
        calculationArea.setColumns(20);
        calculationArea.setRows(5);
        calculationArea.setName("calculationArea "); // NOI18N
        jScrollPane1.setViewportView(calculationArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calculateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(clearButton))
                            .addComponent(ticketIdField))))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ticketIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ticketIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketIdFieldActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:
        calculateHours();

    }//GEN-LAST:event_calculateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        clearFields();

    }//GEN-LAST:event_clearButtonActionPerformed

   private void calculateHours() {
    String ticketId = ticketIdField.getText().trim();

    if (ticketId.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter a Ticket ID");
        return;
    }

    java.util.List<String> ticketLines =
            utils.FileUtil.readAllLines(utils.Constants.TICKETS_FILE);

    models.Ticket ticket = null;

    for (String line : ticketLines) {
        String[] parts = line.split(",");
        if (parts.length >= 7 && parts[0].trim().equals(ticketId)) {
            ticket = new models.Ticket(
                    parts[0].trim(),
                    parts[1].trim(),
                    parts[2].trim(),
                    parts[3].trim(),
                    parts[4].trim(),
                    Double.parseDouble(parts[5].trim()),
                    Boolean.parseBoolean(parts[6].trim())
            );
            break;
        }
    }

    if (ticket == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Ticket not found!");
        return;
    }

    if (ticket.isPaid()) {
        calculationArea.setText(
                "Ticket already paid\nAmount Paid: $" +
                String.format("%.2f", ticket.getAmountPaid())
        );
        return;
    }

    long hours = ticket.getParkedHours();
    if (hours < 1) hours = 1;

    double amountDue = hours * utils.Constants.HOURLY_RATE;

    calculationArea.setText(
            "=== PARKING CALCULATION ===\n" +
            "Ticket ID: " + ticketId + "\n" +
            "Vehicle: " + ticket.getVehiclePlate() + "\n" +
            "Spot: " + ticket.getSpotId() + "\n" +
            "Hours Parked: " + hours + "\n" +
            "Amount Due: $" + String.format("%.2f", amountDue)
    );
}

private void clearFields() {
    ticketIdField.setText("");
    calculationArea.setText("");
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ExitOperator().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextArea calculationArea;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ticketIdField;
    // End of variables declaration//GEN-END:variables
}





